// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnT4cAacevYDO6dcklJhnBB1XowVqxNqQ',
    appId: '1:758107455725:android:a88be776702967a8c14ce4',
    messagingSenderId: '758107455725',
    projectId: 'crypto-app-92b9e',
    storageBucket: 'crypto-app-92b9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlk8xpV2L9hrRKrM4hptjTLTJN4VdVCj4',
    appId: '1:758107455725:ios:21e0ca78f362f6bdc14ce4',
    messagingSenderId: '758107455725',
    projectId: 'crypto-app-92b9e',
    storageBucket: 'crypto-app-92b9e.appspot.com',
    iosBundleId: 'com.dumaks.cryptoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlk8xpV2L9hrRKrM4hptjTLTJN4VdVCj4',
    appId: '1:758107455725:ios:21e0ca78f362f6bdc14ce4',
    messagingSenderId: '758107455725',
    projectId: 'crypto-app-92b9e',
    storageBucket: 'crypto-app-92b9e.appspot.com',
    iosBundleId: 'com.dumaks.cryptoApp',
  );
}
